# Path to sources
#sonar.sources=.
#sonar.exclusions=
#sonar.inclusions=

# Path to tests
#sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=

# sonar-project.properties

sonar.projectKey=axelruiz95_Taller-DevSecOps-CUT26
sonar.organization=axelruiz95
sonar.sources=.

sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/.venv/**,\
**/venv/**,\
**/__pycache__/**,\
**/.pytest_cache/**,\
**/coverage/**,\
**/.next/**,\
**/target/**

# Cobertura JS/TS
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Cobertura Python (si la generas)
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/.pytest_cache/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info