sonar.projectKey=axelruiz95_Taller-DevSecOps-CUT26
sonar.organization=axelruiz95

sonar.sources=.

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/.venv/**,\
  **/venv/**,\
  **/__pycache__/**,\
  **/.pytest_cache/**,\
  **/coverage/**,\
  **/.next/**,\
  **/target/**

sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
